package com.ddup.mybatis.dao;

import com.ddup.mybatis.model.IaAlbum;
import com.ddup.mybatis.model.IaAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IaAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int countByExample(IaAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int deleteByExample(IaAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int insert(IaAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int insertSelective(IaAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    List<IaAlbum> selectByExample(IaAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    IaAlbum selectByPrimaryKey(Long albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IaAlbum record, @Param("example") IaAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IaAlbum record, @Param("example") IaAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IaAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IaAlbum record);
}