package com.ddup.casual.dto.req;

import java.util.Date;

import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.NotBlank;

import com.ddup.base.dto.req.BaseReq;

public class PrivilegeReq extends BaseReq {

	/***************************** validation groups *******************************/

	public interface QueryList {
	}// QueryList

	/**************************** fields *******************************/

	private Integer id;

	@NotBlank(groups = {QueryList.class}, message = "{error.casual.PrivilegeReq.name.NotBlank}")
	@Pattern(groups = {QueryList.class}, regexp = "^[_0-9a-fA-F9fa6~9fff]{10}$", message = "{error.casual.PrivilegeReq.name.Pattern}")
	private String name;// 权限名

	private String actionUrl;

	private Integer parentId;

	private Boolean isMenu;

	private String icon;

	private String description;

	private Date createTime;

	private Date updateTime;

	public PrivilegeReq(Integer id, String name, String actionUrl, Integer parentId, Boolean isMenu, String icon,
			String description, Date createTime, Date updateTime) {
		this.id = id;
		this.name = name;
		this.actionUrl = actionUrl;
		this.parentId = parentId;
		this.isMenu = isMenu;
		this.icon = icon;
		this.description = description;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public PrivilegeReq() {
		super();
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	public String getActionUrl() {
		return actionUrl;
	}

	public void setActionUrl(String actionUrl) {
		this.actionUrl = actionUrl == null ? null : actionUrl.trim();
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Boolean getIsMenu() {
		return isMenu;
	}

	public void setIsMenu(Boolean isMenu) {
		this.isMenu = isMenu;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon == null ? null : icon.trim();
	}

	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_privilege.description
	 *
	 * @param description
	 *            the value for sys_privilege.description
	 *
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_privilege.create_time
	 *
	 * @return the value of sys_privilege.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_privilege.create_time
	 *
	 * @param createTime
	 *            the value for sys_privilege.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_privilege.update_time
	 *
	 * @return the value of sys_privilege.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_privilege.update_time
	 *
	 * @param updateTime
	 *            the value for sys_privilege.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}