package com.ddup.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class IaAddressesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public IaAddressesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAddressidIsNull() {
            addCriterion("addressId is null");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNotNull() {
            addCriterion("addressId is not null");
            return (Criteria) this;
        }

        public Criteria andAddressidEqualTo(Long value) {
            addCriterion("addressId =", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotEqualTo(Long value) {
            addCriterion("addressId <>", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThan(Long value) {
            addCriterion("addressId >", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThanOrEqualTo(Long value) {
            addCriterion("addressId >=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThan(Long value) {
            addCriterion("addressId <", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThanOrEqualTo(Long value) {
            addCriterion("addressId <=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidIn(List<Long> values) {
            addCriterion("addressId in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotIn(List<Long> values) {
            addCriterion("addressId not in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidBetween(Long value1, Long value2) {
            addCriterion("addressId between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotBetween(Long value1, Long value2) {
            addCriterion("addressId not between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNamepyIsNull() {
            addCriterion("namepy is null");
            return (Criteria) this;
        }

        public Criteria andNamepyIsNotNull() {
            addCriterion("namepy is not null");
            return (Criteria) this;
        }

        public Criteria andNamepyEqualTo(String value) {
            addCriterion("namepy =", value, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyNotEqualTo(String value) {
            addCriterion("namepy <>", value, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyGreaterThan(String value) {
            addCriterion("namepy >", value, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyGreaterThanOrEqualTo(String value) {
            addCriterion("namepy >=", value, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyLessThan(String value) {
            addCriterion("namepy <", value, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyLessThanOrEqualTo(String value) {
            addCriterion("namepy <=", value, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyLike(String value) {
            addCriterion("namepy like", value, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyNotLike(String value) {
            addCriterion("namepy not like", value, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyIn(List<String> values) {
            addCriterion("namepy in", values, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyNotIn(List<String> values) {
            addCriterion("namepy not in", values, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyBetween(String value1, String value2) {
            addCriterion("namepy between", value1, value2, "namepy");
            return (Criteria) this;
        }

        public Criteria andNamepyNotBetween(String value1, String value2) {
            addCriterion("namepy not between", value1, value2, "namepy");
            return (Criteria) this;
        }

        public Criteria andOthernameIsNull() {
            addCriterion("othername is null");
            return (Criteria) this;
        }

        public Criteria andOthernameIsNotNull() {
            addCriterion("othername is not null");
            return (Criteria) this;
        }

        public Criteria andOthernameEqualTo(String value) {
            addCriterion("othername =", value, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameNotEqualTo(String value) {
            addCriterion("othername <>", value, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameGreaterThan(String value) {
            addCriterion("othername >", value, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameGreaterThanOrEqualTo(String value) {
            addCriterion("othername >=", value, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameLessThan(String value) {
            addCriterion("othername <", value, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameLessThanOrEqualTo(String value) {
            addCriterion("othername <=", value, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameLike(String value) {
            addCriterion("othername like", value, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameNotLike(String value) {
            addCriterion("othername not like", value, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameIn(List<String> values) {
            addCriterion("othername in", values, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameNotIn(List<String> values) {
            addCriterion("othername not in", values, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameBetween(String value1, String value2) {
            addCriterion("othername between", value1, value2, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernameNotBetween(String value1, String value2) {
            addCriterion("othername not between", value1, value2, "othername");
            return (Criteria) this;
        }

        public Criteria andOthernamepyIsNull() {
            addCriterion("othernamepy is null");
            return (Criteria) this;
        }

        public Criteria andOthernamepyIsNotNull() {
            addCriterion("othernamepy is not null");
            return (Criteria) this;
        }

        public Criteria andOthernamepyEqualTo(String value) {
            addCriterion("othernamepy =", value, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyNotEqualTo(String value) {
            addCriterion("othernamepy <>", value, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyGreaterThan(String value) {
            addCriterion("othernamepy >", value, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyGreaterThanOrEqualTo(String value) {
            addCriterion("othernamepy >=", value, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyLessThan(String value) {
            addCriterion("othernamepy <", value, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyLessThanOrEqualTo(String value) {
            addCriterion("othernamepy <=", value, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyLike(String value) {
            addCriterion("othernamepy like", value, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyNotLike(String value) {
            addCriterion("othernamepy not like", value, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyIn(List<String> values) {
            addCriterion("othernamepy in", values, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyNotIn(List<String> values) {
            addCriterion("othernamepy not in", values, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyBetween(String value1, String value2) {
            addCriterion("othernamepy between", value1, value2, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOthernamepyNotBetween(String value1, String value2) {
            addCriterion("othernamepy not between", value1, value2, "othernamepy");
            return (Criteria) this;
        }

        public Criteria andOldnameIsNull() {
            addCriterion("oldname is null");
            return (Criteria) this;
        }

        public Criteria andOldnameIsNotNull() {
            addCriterion("oldname is not null");
            return (Criteria) this;
        }

        public Criteria andOldnameEqualTo(String value) {
            addCriterion("oldname =", value, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameNotEqualTo(String value) {
            addCriterion("oldname <>", value, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameGreaterThan(String value) {
            addCriterion("oldname >", value, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameGreaterThanOrEqualTo(String value) {
            addCriterion("oldname >=", value, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameLessThan(String value) {
            addCriterion("oldname <", value, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameLessThanOrEqualTo(String value) {
            addCriterion("oldname <=", value, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameLike(String value) {
            addCriterion("oldname like", value, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameNotLike(String value) {
            addCriterion("oldname not like", value, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameIn(List<String> values) {
            addCriterion("oldname in", values, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameNotIn(List<String> values) {
            addCriterion("oldname not in", values, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameBetween(String value1, String value2) {
            addCriterion("oldname between", value1, value2, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnameNotBetween(String value1, String value2) {
            addCriterion("oldname not between", value1, value2, "oldname");
            return (Criteria) this;
        }

        public Criteria andOldnamepyIsNull() {
            addCriterion("oldnamepy is null");
            return (Criteria) this;
        }

        public Criteria andOldnamepyIsNotNull() {
            addCriterion("oldnamepy is not null");
            return (Criteria) this;
        }

        public Criteria andOldnamepyEqualTo(String value) {
            addCriterion("oldnamepy =", value, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyNotEqualTo(String value) {
            addCriterion("oldnamepy <>", value, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyGreaterThan(String value) {
            addCriterion("oldnamepy >", value, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyGreaterThanOrEqualTo(String value) {
            addCriterion("oldnamepy >=", value, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyLessThan(String value) {
            addCriterion("oldnamepy <", value, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyLessThanOrEqualTo(String value) {
            addCriterion("oldnamepy <=", value, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyLike(String value) {
            addCriterion("oldnamepy like", value, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyNotLike(String value) {
            addCriterion("oldnamepy not like", value, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyIn(List<String> values) {
            addCriterion("oldnamepy in", values, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyNotIn(List<String> values) {
            addCriterion("oldnamepy not in", values, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyBetween(String value1, String value2) {
            addCriterion("oldnamepy between", value1, value2, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andOldnamepyNotBetween(String value1, String value2) {
            addCriterion("oldnamepy not between", value1, value2, "oldnamepy");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIsNull() {
            addCriterion("englishname is null");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIsNotNull() {
            addCriterion("englishname is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishnameEqualTo(String value) {
            addCriterion("englishname =", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotEqualTo(String value) {
            addCriterion("englishname <>", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameGreaterThan(String value) {
            addCriterion("englishname >", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameGreaterThanOrEqualTo(String value) {
            addCriterion("englishname >=", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLessThan(String value) {
            addCriterion("englishname <", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLessThanOrEqualTo(String value) {
            addCriterion("englishname <=", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLike(String value) {
            addCriterion("englishname like", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotLike(String value) {
            addCriterion("englishname not like", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIn(List<String> values) {
            addCriterion("englishname in", values, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotIn(List<String> values) {
            addCriterion("englishname not in", values, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameBetween(String value1, String value2) {
            addCriterion("englishname between", value1, value2, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotBetween(String value1, String value2) {
            addCriterion("englishname not between", value1, value2, "englishname");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNull() {
            addCriterion("telephone is null");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNotNull() {
            addCriterion("telephone is not null");
            return (Criteria) this;
        }

        public Criteria andTelephoneEqualTo(String value) {
            addCriterion("telephone =", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotEqualTo(String value) {
            addCriterion("telephone <>", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThan(String value) {
            addCriterion("telephone >", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("telephone >=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThan(String value) {
            addCriterion("telephone <", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThanOrEqualTo(String value) {
            addCriterion("telephone <=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLike(String value) {
            addCriterion("telephone like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotLike(String value) {
            addCriterion("telephone not like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneIn(List<String> values) {
            addCriterion("telephone in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotIn(List<String> values) {
            addCriterion("telephone not in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneBetween(String value1, String value2) {
            addCriterion("telephone between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotBetween(String value1, String value2) {
            addCriterion("telephone not between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNull() {
            addCriterion("zipcode is null");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNotNull() {
            addCriterion("zipcode is not null");
            return (Criteria) this;
        }

        public Criteria andZipcodeEqualTo(String value) {
            addCriterion("zipcode =", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotEqualTo(String value) {
            addCriterion("zipcode <>", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThan(String value) {
            addCriterion("zipcode >", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("zipcode >=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThan(String value) {
            addCriterion("zipcode <", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThanOrEqualTo(String value) {
            addCriterion("zipcode <=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLike(String value) {
            addCriterion("zipcode like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotLike(String value) {
            addCriterion("zipcode not like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeIn(List<String> values) {
            addCriterion("zipcode in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotIn(List<String> values) {
            addCriterion("zipcode not in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeBetween(String value1, String value2) {
            addCriterion("zipcode between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotBetween(String value1, String value2) {
            addCriterion("zipcode not between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andCitycodeIsNull() {
            addCriterion("citycode is null");
            return (Criteria) this;
        }

        public Criteria andCitycodeIsNotNull() {
            addCriterion("citycode is not null");
            return (Criteria) this;
        }

        public Criteria andCitycodeEqualTo(String value) {
            addCriterion("citycode =", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotEqualTo(String value) {
            addCriterion("citycode <>", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeGreaterThan(String value) {
            addCriterion("citycode >", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeGreaterThanOrEqualTo(String value) {
            addCriterion("citycode >=", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLessThan(String value) {
            addCriterion("citycode <", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLessThanOrEqualTo(String value) {
            addCriterion("citycode <=", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLike(String value) {
            addCriterion("citycode like", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotLike(String value) {
            addCriterion("citycode not like", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeIn(List<String> values) {
            addCriterion("citycode in", values, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotIn(List<String> values) {
            addCriterion("citycode not in", values, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeBetween(String value1, String value2) {
            addCriterion("citycode between", value1, value2, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotBetween(String value1, String value2) {
            addCriterion("citycode not between", value1, value2, "citycode");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDisplayxIsNull() {
            addCriterion("displayX is null");
            return (Criteria) this;
        }

        public Criteria andDisplayxIsNotNull() {
            addCriterion("displayX is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayxEqualTo(Double value) {
            addCriterion("displayX =", value, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxNotEqualTo(Double value) {
            addCriterion("displayX <>", value, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxGreaterThan(Double value) {
            addCriterion("displayX >", value, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxGreaterThanOrEqualTo(Double value) {
            addCriterion("displayX >=", value, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxLessThan(Double value) {
            addCriterion("displayX <", value, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxLessThanOrEqualTo(Double value) {
            addCriterion("displayX <=", value, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxIn(List<Double> values) {
            addCriterion("displayX in", values, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxNotIn(List<Double> values) {
            addCriterion("displayX not in", values, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxBetween(Double value1, Double value2) {
            addCriterion("displayX between", value1, value2, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayxNotBetween(Double value1, Double value2) {
            addCriterion("displayX not between", value1, value2, "displayx");
            return (Criteria) this;
        }

        public Criteria andDisplayyIsNull() {
            addCriterion("displayY is null");
            return (Criteria) this;
        }

        public Criteria andDisplayyIsNotNull() {
            addCriterion("displayY is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayyEqualTo(Double value) {
            addCriterion("displayY =", value, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyNotEqualTo(Double value) {
            addCriterion("displayY <>", value, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyGreaterThan(Double value) {
            addCriterion("displayY >", value, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyGreaterThanOrEqualTo(Double value) {
            addCriterion("displayY >=", value, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyLessThan(Double value) {
            addCriterion("displayY <", value, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyLessThanOrEqualTo(Double value) {
            addCriterion("displayY <=", value, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyIn(List<Double> values) {
            addCriterion("displayY in", values, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyNotIn(List<Double> values) {
            addCriterion("displayY not in", values, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyBetween(Double value1, Double value2) {
            addCriterion("displayY between", value1, value2, "displayy");
            return (Criteria) this;
        }

        public Criteria andDisplayyNotBetween(Double value1, Double value2) {
            addCriterion("displayY not between", value1, value2, "displayy");
            return (Criteria) this;
        }

        public Criteria andDlongitudeIsNull() {
            addCriterion("dlongitude is null");
            return (Criteria) this;
        }

        public Criteria andDlongitudeIsNotNull() {
            addCriterion("dlongitude is not null");
            return (Criteria) this;
        }

        public Criteria andDlongitudeEqualTo(Double value) {
            addCriterion("dlongitude =", value, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeNotEqualTo(Double value) {
            addCriterion("dlongitude <>", value, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeGreaterThan(Double value) {
            addCriterion("dlongitude >", value, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("dlongitude >=", value, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeLessThan(Double value) {
            addCriterion("dlongitude <", value, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeLessThanOrEqualTo(Double value) {
            addCriterion("dlongitude <=", value, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeIn(List<Double> values) {
            addCriterion("dlongitude in", values, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeNotIn(List<Double> values) {
            addCriterion("dlongitude not in", values, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeBetween(Double value1, Double value2) {
            addCriterion("dlongitude between", value1, value2, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlongitudeNotBetween(Double value1, Double value2) {
            addCriterion("dlongitude not between", value1, value2, "dlongitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeIsNull() {
            addCriterion("dlatitude is null");
            return (Criteria) this;
        }

        public Criteria andDlatitudeIsNotNull() {
            addCriterion("dlatitude is not null");
            return (Criteria) this;
        }

        public Criteria andDlatitudeEqualTo(Double value) {
            addCriterion("dlatitude =", value, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeNotEqualTo(Double value) {
            addCriterion("dlatitude <>", value, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeGreaterThan(Double value) {
            addCriterion("dlatitude >", value, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("dlatitude >=", value, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeLessThan(Double value) {
            addCriterion("dlatitude <", value, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeLessThanOrEqualTo(Double value) {
            addCriterion("dlatitude <=", value, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeIn(List<Double> values) {
            addCriterion("dlatitude in", values, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeNotIn(List<Double> values) {
            addCriterion("dlatitude not in", values, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeBetween(Double value1, Double value2) {
            addCriterion("dlatitude between", value1, value2, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andDlatitudeNotBetween(Double value1, Double value2) {
            addCriterion("dlatitude not between", value1, value2, "dlatitude");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterionForJDBCDate("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterionForJDBCDate("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterionForJDBCDate("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterionForJDBCDate("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterionForJDBCDate("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterionForJDBCDate("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeIsNull() {
            addCriterion("updatetTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeIsNotNull() {
            addCriterion("updatetTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeEqualTo(Date value) {
            addCriterionForJDBCDate("updatetTime =", value, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("updatetTime <>", value, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeGreaterThan(Date value) {
            addCriterionForJDBCDate("updatetTime >", value, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("updatetTime >=", value, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeLessThan(Date value) {
            addCriterionForJDBCDate("updatetTime <", value, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("updatetTime <=", value, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeIn(List<Date> values) {
            addCriterionForJDBCDate("updatetTime in", values, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("updatetTime not in", values, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("updatetTime between", value1, value2, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUpdatettimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("updatetTime not between", value1, value2, "updatettime");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andImailIsNull() {
            addCriterion("imail is null");
            return (Criteria) this;
        }

        public Criteria andImailIsNotNull() {
            addCriterion("imail is not null");
            return (Criteria) this;
        }

        public Criteria andImailEqualTo(String value) {
            addCriterion("imail =", value, "imail");
            return (Criteria) this;
        }

        public Criteria andImailNotEqualTo(String value) {
            addCriterion("imail <>", value, "imail");
            return (Criteria) this;
        }

        public Criteria andImailGreaterThan(String value) {
            addCriterion("imail >", value, "imail");
            return (Criteria) this;
        }

        public Criteria andImailGreaterThanOrEqualTo(String value) {
            addCriterion("imail >=", value, "imail");
            return (Criteria) this;
        }

        public Criteria andImailLessThan(String value) {
            addCriterion("imail <", value, "imail");
            return (Criteria) this;
        }

        public Criteria andImailLessThanOrEqualTo(String value) {
            addCriterion("imail <=", value, "imail");
            return (Criteria) this;
        }

        public Criteria andImailLike(String value) {
            addCriterion("imail like", value, "imail");
            return (Criteria) this;
        }

        public Criteria andImailNotLike(String value) {
            addCriterion("imail not like", value, "imail");
            return (Criteria) this;
        }

        public Criteria andImailIn(List<String> values) {
            addCriterion("imail in", values, "imail");
            return (Criteria) this;
        }

        public Criteria andImailNotIn(List<String> values) {
            addCriterion("imail not in", values, "imail");
            return (Criteria) this;
        }

        public Criteria andImailBetween(String value1, String value2) {
            addCriterion("imail between", value1, value2, "imail");
            return (Criteria) this;
        }

        public Criteria andImailNotBetween(String value1, String value2) {
            addCriterion("imail not between", value1, value2, "imail");
            return (Criteria) this;
        }

        public Criteria andAuditingstateIsNull() {
            addCriterion("auditingState is null");
            return (Criteria) this;
        }

        public Criteria andAuditingstateIsNotNull() {
            addCriterion("auditingState is not null");
            return (Criteria) this;
        }

        public Criteria andAuditingstateEqualTo(String value) {
            addCriterion("auditingState =", value, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateNotEqualTo(String value) {
            addCriterion("auditingState <>", value, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateGreaterThan(String value) {
            addCriterion("auditingState >", value, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateGreaterThanOrEqualTo(String value) {
            addCriterion("auditingState >=", value, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateLessThan(String value) {
            addCriterion("auditingState <", value, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateLessThanOrEqualTo(String value) {
            addCriterion("auditingState <=", value, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateLike(String value) {
            addCriterion("auditingState like", value, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateNotLike(String value) {
            addCriterion("auditingState not like", value, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateIn(List<String> values) {
            addCriterion("auditingState in", values, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateNotIn(List<String> values) {
            addCriterion("auditingState not in", values, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateBetween(String value1, String value2) {
            addCriterion("auditingState between", value1, value2, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andAuditingstateNotBetween(String value1, String value2) {
            addCriterion("auditingState not between", value1, value2, "auditingstate");
            return (Criteria) this;
        }

        public Criteria andImportanceIsNull() {
            addCriterion("importance is null");
            return (Criteria) this;
        }

        public Criteria andImportanceIsNotNull() {
            addCriterion("importance is not null");
            return (Criteria) this;
        }

        public Criteria andImportanceEqualTo(String value) {
            addCriterion("importance =", value, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceNotEqualTo(String value) {
            addCriterion("importance <>", value, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceGreaterThan(String value) {
            addCriterion("importance >", value, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceGreaterThanOrEqualTo(String value) {
            addCriterion("importance >=", value, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceLessThan(String value) {
            addCriterion("importance <", value, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceLessThanOrEqualTo(String value) {
            addCriterion("importance <=", value, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceLike(String value) {
            addCriterion("importance like", value, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceNotLike(String value) {
            addCriterion("importance not like", value, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceIn(List<String> values) {
            addCriterion("importance in", values, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceNotIn(List<String> values) {
            addCriterion("importance not in", values, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceBetween(String value1, String value2) {
            addCriterion("importance between", value1, value2, "importance");
            return (Criteria) this;
        }

        public Criteria andImportanceNotBetween(String value1, String value2) {
            addCriterion("importance not between", value1, value2, "importance");
            return (Criteria) this;
        }

        public Criteria andTagIsNull() {
            addCriterion("tag is null");
            return (Criteria) this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("tag is not null");
            return (Criteria) this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("tag =", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("tag <>", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("tag >", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("tag >=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("tag <", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("tag <=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("tag like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("tag not like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagIn(List<String> values) {
            addCriterion("tag in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotIn(List<String> values) {
            addCriterion("tag not in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("tag between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("tag not between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andPapoiIsNull() {
            addCriterion("papoi is null");
            return (Criteria) this;
        }

        public Criteria andPapoiIsNotNull() {
            addCriterion("papoi is not null");
            return (Criteria) this;
        }

        public Criteria andPapoiEqualTo(String value) {
            addCriterion("papoi =", value, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiNotEqualTo(String value) {
            addCriterion("papoi <>", value, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiGreaterThan(String value) {
            addCriterion("papoi >", value, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiGreaterThanOrEqualTo(String value) {
            addCriterion("papoi >=", value, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiLessThan(String value) {
            addCriterion("papoi <", value, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiLessThanOrEqualTo(String value) {
            addCriterion("papoi <=", value, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiLike(String value) {
            addCriterion("papoi like", value, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiNotLike(String value) {
            addCriterion("papoi not like", value, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiIn(List<String> values) {
            addCriterion("papoi in", values, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiNotIn(List<String> values) {
            addCriterion("papoi not in", values, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiBetween(String value1, String value2) {
            addCriterion("papoi between", value1, value2, "papoi");
            return (Criteria) this;
        }

        public Criteria andPapoiNotBetween(String value1, String value2) {
            addCriterion("papoi not between", value1, value2, "papoi");
            return (Criteria) this;
        }

        public Criteria andDatasourceidIsNull() {
            addCriterion("datasourceId is null");
            return (Criteria) this;
        }

        public Criteria andDatasourceidIsNotNull() {
            addCriterion("datasourceId is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourceidEqualTo(String value) {
            addCriterion("datasourceId =", value, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidNotEqualTo(String value) {
            addCriterion("datasourceId <>", value, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidGreaterThan(String value) {
            addCriterion("datasourceId >", value, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidGreaterThanOrEqualTo(String value) {
            addCriterion("datasourceId >=", value, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidLessThan(String value) {
            addCriterion("datasourceId <", value, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidLessThanOrEqualTo(String value) {
            addCriterion("datasourceId <=", value, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidLike(String value) {
            addCriterion("datasourceId like", value, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidNotLike(String value) {
            addCriterion("datasourceId not like", value, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidIn(List<String> values) {
            addCriterion("datasourceId in", values, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidNotIn(List<String> values) {
            addCriterion("datasourceId not in", values, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidBetween(String value1, String value2) {
            addCriterion("datasourceId between", value1, value2, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andDatasourceidNotBetween(String value1, String value2) {
            addCriterion("datasourceId not between", value1, value2, "datasourceid");
            return (Criteria) this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("brand is null");
            return (Criteria) this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("brand is not null");
            return (Criteria) this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("brand =", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("brand <>", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("brand >", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("brand >=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("brand <", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("brand <=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("brand like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("brand not like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandIn(List<String> values) {
            addCriterion("brand in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotIn(List<String> values) {
            addCriterion("brand not in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("brand between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("brand not between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andPositioncodeIsNull() {
            addCriterion("positionCode is null");
            return (Criteria) this;
        }

        public Criteria andPositioncodeIsNotNull() {
            addCriterion("positionCode is not null");
            return (Criteria) this;
        }

        public Criteria andPositioncodeEqualTo(String value) {
            addCriterion("positionCode =", value, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeNotEqualTo(String value) {
            addCriterion("positionCode <>", value, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeGreaterThan(String value) {
            addCriterion("positionCode >", value, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeGreaterThanOrEqualTo(String value) {
            addCriterion("positionCode >=", value, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeLessThan(String value) {
            addCriterion("positionCode <", value, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeLessThanOrEqualTo(String value) {
            addCriterion("positionCode <=", value, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeLike(String value) {
            addCriterion("positionCode like", value, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeNotLike(String value) {
            addCriterion("positionCode not like", value, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeIn(List<String> values) {
            addCriterion("positionCode in", values, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeNotIn(List<String> values) {
            addCriterion("positionCode not in", values, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeBetween(String value1, String value2) {
            addCriterion("positionCode between", value1, value2, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPositioncodeNotBetween(String value1, String value2) {
            addCriterion("positionCode not between", value1, value2, "positioncode");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("pid like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("pid not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIsNull() {
            addCriterion("abbreviation is null");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIsNotNull() {
            addCriterion("abbreviation is not null");
            return (Criteria) this;
        }

        public Criteria andAbbreviationEqualTo(String value) {
            addCriterion("abbreviation =", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotEqualTo(String value) {
            addCriterion("abbreviation <>", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationGreaterThan(String value) {
            addCriterion("abbreviation >", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationGreaterThanOrEqualTo(String value) {
            addCriterion("abbreviation >=", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLessThan(String value) {
            addCriterion("abbreviation <", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLessThanOrEqualTo(String value) {
            addCriterion("abbreviation <=", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLike(String value) {
            addCriterion("abbreviation like", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotLike(String value) {
            addCriterion("abbreviation not like", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIn(List<String> values) {
            addCriterion("abbreviation in", values, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotIn(List<String> values) {
            addCriterion("abbreviation not in", values, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationBetween(String value1, String value2) {
            addCriterion("abbreviation between", value1, value2, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotBetween(String value1, String value2) {
            addCriterion("abbreviation not between", value1, value2, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andGeonumIsNull() {
            addCriterion("geoNum is null");
            return (Criteria) this;
        }

        public Criteria andGeonumIsNotNull() {
            addCriterion("geoNum is not null");
            return (Criteria) this;
        }

        public Criteria andGeonumEqualTo(Long value) {
            addCriterion("geoNum =", value, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumNotEqualTo(Long value) {
            addCriterion("geoNum <>", value, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumGreaterThan(Long value) {
            addCriterion("geoNum >", value, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumGreaterThanOrEqualTo(Long value) {
            addCriterion("geoNum >=", value, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumLessThan(Long value) {
            addCriterion("geoNum <", value, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumLessThanOrEqualTo(Long value) {
            addCriterion("geoNum <=", value, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumIn(List<Long> values) {
            addCriterion("geoNum in", values, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumNotIn(List<Long> values) {
            addCriterion("geoNum not in", values, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumBetween(Long value1, Long value2) {
            addCriterion("geoNum between", value1, value2, "geonum");
            return (Criteria) this;
        }

        public Criteria andGeonumNotBetween(Long value1, Long value2) {
            addCriterion("geoNum not between", value1, value2, "geonum");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andAlbumidIsNull() {
            addCriterion("albumId is null");
            return (Criteria) this;
        }

        public Criteria andAlbumidIsNotNull() {
            addCriterion("albumId is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumidEqualTo(Long value) {
            addCriterion("albumId =", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidNotEqualTo(Long value) {
            addCriterion("albumId <>", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidGreaterThan(Long value) {
            addCriterion("albumId >", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidGreaterThanOrEqualTo(Long value) {
            addCriterion("albumId >=", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidLessThan(Long value) {
            addCriterion("albumId <", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidLessThanOrEqualTo(Long value) {
            addCriterion("albumId <=", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidIn(List<Long> values) {
            addCriterion("albumId in", values, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidNotIn(List<Long> values) {
            addCriterion("albumId not in", values, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidBetween(Long value1, Long value2) {
            addCriterion("albumId between", value1, value2, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidNotBetween(Long value1, Long value2) {
            addCriterion("albumId not between", value1, value2, "albumid");
            return (Criteria) this;
        }

        public Criteria andGeoLevelIsNull() {
            addCriterion("geo_level is null");
            return (Criteria) this;
        }

        public Criteria andGeoLevelIsNotNull() {
            addCriterion("geo_level is not null");
            return (Criteria) this;
        }

        public Criteria andGeoLevelEqualTo(Integer value) {
            addCriterion("geo_level =", value, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelNotEqualTo(Integer value) {
            addCriterion("geo_level <>", value, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelGreaterThan(Integer value) {
            addCriterion("geo_level >", value, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("geo_level >=", value, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelLessThan(Integer value) {
            addCriterion("geo_level <", value, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelLessThanOrEqualTo(Integer value) {
            addCriterion("geo_level <=", value, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelIn(List<Integer> values) {
            addCriterion("geo_level in", values, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelNotIn(List<Integer> values) {
            addCriterion("geo_level not in", values, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelBetween(Integer value1, Integer value2) {
            addCriterion("geo_level between", value1, value2, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andGeoLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("geo_level not between", value1, value2, "geoLevel");
            return (Criteria) this;
        }

        public Criteria andCoverPicIsNull() {
            addCriterion("cover_pic is null");
            return (Criteria) this;
        }

        public Criteria andCoverPicIsNotNull() {
            addCriterion("cover_pic is not null");
            return (Criteria) this;
        }

        public Criteria andCoverPicEqualTo(String value) {
            addCriterion("cover_pic =", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicNotEqualTo(String value) {
            addCriterion("cover_pic <>", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicGreaterThan(String value) {
            addCriterion("cover_pic >", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicGreaterThanOrEqualTo(String value) {
            addCriterion("cover_pic >=", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicLessThan(String value) {
            addCriterion("cover_pic <", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicLessThanOrEqualTo(String value) {
            addCriterion("cover_pic <=", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicLike(String value) {
            addCriterion("cover_pic like", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicNotLike(String value) {
            addCriterion("cover_pic not like", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicIn(List<String> values) {
            addCriterion("cover_pic in", values, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicNotIn(List<String> values) {
            addCriterion("cover_pic not in", values, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicBetween(String value1, String value2) {
            addCriterion("cover_pic between", value1, value2, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicNotBetween(String value1, String value2) {
            addCriterion("cover_pic not between", value1, value2, "coverPic");
            return (Criteria) this;
        }

        public Criteria andShouhuiIsNull() {
            addCriterion("shouhui is null");
            return (Criteria) this;
        }

        public Criteria andShouhuiIsNotNull() {
            addCriterion("shouhui is not null");
            return (Criteria) this;
        }

        public Criteria andShouhuiEqualTo(Long value) {
            addCriterion("shouhui =", value, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiNotEqualTo(Long value) {
            addCriterion("shouhui <>", value, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiGreaterThan(Long value) {
            addCriterion("shouhui >", value, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiGreaterThanOrEqualTo(Long value) {
            addCriterion("shouhui >=", value, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiLessThan(Long value) {
            addCriterion("shouhui <", value, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiLessThanOrEqualTo(Long value) {
            addCriterion("shouhui <=", value, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiIn(List<Long> values) {
            addCriterion("shouhui in", values, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiNotIn(List<Long> values) {
            addCriterion("shouhui not in", values, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiBetween(Long value1, Long value2) {
            addCriterion("shouhui between", value1, value2, "shouhui");
            return (Criteria) this;
        }

        public Criteria andShouhuiNotBetween(Long value1, Long value2) {
            addCriterion("shouhui not between", value1, value2, "shouhui");
            return (Criteria) this;
        }

        public Criteria andRelativelocationIsNull() {
            addCriterion("relativeLocation is null");
            return (Criteria) this;
        }

        public Criteria andRelativelocationIsNotNull() {
            addCriterion("relativeLocation is not null");
            return (Criteria) this;
        }

        public Criteria andRelativelocationEqualTo(String value) {
            addCriterion("relativeLocation =", value, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationNotEqualTo(String value) {
            addCriterion("relativeLocation <>", value, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationGreaterThan(String value) {
            addCriterion("relativeLocation >", value, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationGreaterThanOrEqualTo(String value) {
            addCriterion("relativeLocation >=", value, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationLessThan(String value) {
            addCriterion("relativeLocation <", value, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationLessThanOrEqualTo(String value) {
            addCriterion("relativeLocation <=", value, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationLike(String value) {
            addCriterion("relativeLocation like", value, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationNotLike(String value) {
            addCriterion("relativeLocation not like", value, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationIn(List<String> values) {
            addCriterion("relativeLocation in", values, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationNotIn(List<String> values) {
            addCriterion("relativeLocation not in", values, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationBetween(String value1, String value2) {
            addCriterion("relativeLocation between", value1, value2, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andRelativelocationNotBetween(String value1, String value2) {
            addCriterion("relativeLocation not between", value1, value2, "relativelocation");
            return (Criteria) this;
        }

        public Criteria andContactsIsNull() {
            addCriterion("contacts is null");
            return (Criteria) this;
        }

        public Criteria andContactsIsNotNull() {
            addCriterion("contacts is not null");
            return (Criteria) this;
        }

        public Criteria andContactsEqualTo(String value) {
            addCriterion("contacts =", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsNotEqualTo(String value) {
            addCriterion("contacts <>", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsGreaterThan(String value) {
            addCriterion("contacts >", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsGreaterThanOrEqualTo(String value) {
            addCriterion("contacts >=", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsLessThan(String value) {
            addCriterion("contacts <", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsLessThanOrEqualTo(String value) {
            addCriterion("contacts <=", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsLike(String value) {
            addCriterion("contacts like", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsNotLike(String value) {
            addCriterion("contacts not like", value, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsIn(List<String> values) {
            addCriterion("contacts in", values, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsNotIn(List<String> values) {
            addCriterion("contacts not in", values, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsBetween(String value1, String value2) {
            addCriterion("contacts between", value1, value2, "contacts");
            return (Criteria) this;
        }

        public Criteria andContactsNotBetween(String value1, String value2) {
            addCriterion("contacts not between", value1, value2, "contacts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ia_addresses
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}