package com.ddup.mybatis.model;

public class IaCategories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_categories.categoryId
     *
     * @mbggenerated
     */
    private Long categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_categories.categoryName
     *
     * @mbggenerated
     */
    private String categoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_categories.parentId
     *
     * @mbggenerated
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_categories.privateFlag
     *
     * @mbggenerated
     */
    private String privateflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_categories.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_categories.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_categories
     *
     * @mbggenerated
     */
    public IaCategories(Long categoryid, String categoryname, Long parentid, String privateflag, Long userid, String icon) {
        this.categoryid = categoryid;
        this.categoryname = categoryname;
        this.parentid = parentid;
        this.privateflag = privateflag;
        this.userid = userid;
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_categories
     *
     * @mbggenerated
     */
    public IaCategories() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_categories.categoryId
     *
     * @return the value of ia_categories.categoryId
     *
     * @mbggenerated
     */
    public Long getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_categories.categoryId
     *
     * @param categoryid the value for ia_categories.categoryId
     *
     * @mbggenerated
     */
    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_categories.categoryName
     *
     * @return the value of ia_categories.categoryName
     *
     * @mbggenerated
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_categories.categoryName
     *
     * @param categoryname the value for ia_categories.categoryName
     *
     * @mbggenerated
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_categories.parentId
     *
     * @return the value of ia_categories.parentId
     *
     * @mbggenerated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_categories.parentId
     *
     * @param parentid the value for ia_categories.parentId
     *
     * @mbggenerated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_categories.privateFlag
     *
     * @return the value of ia_categories.privateFlag
     *
     * @mbggenerated
     */
    public String getPrivateflag() {
        return privateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_categories.privateFlag
     *
     * @param privateflag the value for ia_categories.privateFlag
     *
     * @mbggenerated
     */
    public void setPrivateflag(String privateflag) {
        this.privateflag = privateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_categories.userId
     *
     * @return the value of ia_categories.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_categories.userId
     *
     * @param userid the value for ia_categories.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_categories.icon
     *
     * @return the value of ia_categories.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_categories.icon
     *
     * @param icon the value for ia_categories.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}