package com.ddup.mybatis.model;

public class IaCollected {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.collectId
     *
     * @mbggenerated
     */
    private Long collectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.cover_pic
     *
     * @mbggenerated
     */
    private String coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.firstLetter
     *
     * @mbggenerated
     */
    private String firstletter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.addressId
     *
     * @mbggenerated
     */
    private Long addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.deleteClass
     *
     * @mbggenerated
     */
    private Integer deleteclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.albumId
     *
     * @mbggenerated
     */
    private Long albumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.sketch_albumId
     *
     * @mbggenerated
     */
    private Long sketchAlbumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.video_set_id
     *
     * @mbggenerated
     */
    private Long videoSetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_collected.categoryId
     *
     * @mbggenerated
     */
    private Long categoryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public IaCollected(Long collectid, String coverPic, String firstletter, Long addressid, Long userid, String name, Integer deleteclass, String remark, Long albumid, Long sketchAlbumid, Long videoSetId, Long categoryid) {
        this.collectid = collectid;
        this.coverPic = coverPic;
        this.firstletter = firstletter;
        this.addressid = addressid;
        this.userid = userid;
        this.name = name;
        this.deleteclass = deleteclass;
        this.remark = remark;
        this.albumid = albumid;
        this.sketchAlbumid = sketchAlbumid;
        this.videoSetId = videoSetId;
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public IaCollected() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.collectId
     *
     * @return the value of ia_collected.collectId
     *
     * @mbggenerated
     */
    public Long getCollectid() {
        return collectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.collectId
     *
     * @param collectid the value for ia_collected.collectId
     *
     * @mbggenerated
     */
    public void setCollectid(Long collectid) {
        this.collectid = collectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.cover_pic
     *
     * @return the value of ia_collected.cover_pic
     *
     * @mbggenerated
     */
    public String getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.cover_pic
     *
     * @param coverPic the value for ia_collected.cover_pic
     *
     * @mbggenerated
     */
    public void setCoverPic(String coverPic) {
        this.coverPic = coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.firstLetter
     *
     * @return the value of ia_collected.firstLetter
     *
     * @mbggenerated
     */
    public String getFirstletter() {
        return firstletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.firstLetter
     *
     * @param firstletter the value for ia_collected.firstLetter
     *
     * @mbggenerated
     */
    public void setFirstletter(String firstletter) {
        this.firstletter = firstletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.addressId
     *
     * @return the value of ia_collected.addressId
     *
     * @mbggenerated
     */
    public Long getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.addressId
     *
     * @param addressid the value for ia_collected.addressId
     *
     * @mbggenerated
     */
    public void setAddressid(Long addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.userId
     *
     * @return the value of ia_collected.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.userId
     *
     * @param userid the value for ia_collected.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.name
     *
     * @return the value of ia_collected.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.name
     *
     * @param name the value for ia_collected.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.deleteClass
     *
     * @return the value of ia_collected.deleteClass
     *
     * @mbggenerated
     */
    public Integer getDeleteclass() {
        return deleteclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.deleteClass
     *
     * @param deleteclass the value for ia_collected.deleteClass
     *
     * @mbggenerated
     */
    public void setDeleteclass(Integer deleteclass) {
        this.deleteclass = deleteclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.remark
     *
     * @return the value of ia_collected.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.remark
     *
     * @param remark the value for ia_collected.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.albumId
     *
     * @return the value of ia_collected.albumId
     *
     * @mbggenerated
     */
    public Long getAlbumid() {
        return albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.albumId
     *
     * @param albumid the value for ia_collected.albumId
     *
     * @mbggenerated
     */
    public void setAlbumid(Long albumid) {
        this.albumid = albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.sketch_albumId
     *
     * @return the value of ia_collected.sketch_albumId
     *
     * @mbggenerated
     */
    public Long getSketchAlbumid() {
        return sketchAlbumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.sketch_albumId
     *
     * @param sketchAlbumid the value for ia_collected.sketch_albumId
     *
     * @mbggenerated
     */
    public void setSketchAlbumid(Long sketchAlbumid) {
        this.sketchAlbumid = sketchAlbumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.video_set_id
     *
     * @return the value of ia_collected.video_set_id
     *
     * @mbggenerated
     */
    public Long getVideoSetId() {
        return videoSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.video_set_id
     *
     * @param videoSetId the value for ia_collected.video_set_id
     *
     * @mbggenerated
     */
    public void setVideoSetId(Long videoSetId) {
        this.videoSetId = videoSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_collected.categoryId
     *
     * @return the value of ia_collected.categoryId
     *
     * @mbggenerated
     */
    public Long getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_collected.categoryId
     *
     * @param categoryid the value for ia_collected.categoryId
     *
     * @mbggenerated
     */
    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }
}