package com.iwhere.mybatis.model;

import java.util.Date;

public class IaAddresses {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.addressId
     *
     * @mbggenerated
     */
    private Long addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.namepy
     *
     * @mbggenerated
     */
    private String namepy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.othername
     *
     * @mbggenerated
     */
    private String othername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.othernamepy
     *
     * @mbggenerated
     */
    private String othernamepy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.oldname
     *
     * @mbggenerated
     */
    private String oldname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.oldnamepy
     *
     * @mbggenerated
     */
    private String oldnamepy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.englishname
     *
     * @mbggenerated
     */
    private String englishname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.zipcode
     *
     * @mbggenerated
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.citycode
     *
     * @mbggenerated
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.displayX
     *
     * @mbggenerated
     */
    private Double displayx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.displayY
     *
     * @mbggenerated
     */
    private Double displayy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.dlongitude
     *
     * @mbggenerated
     */
    private Double dlongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.dlatitude
     *
     * @mbggenerated
     */
    private Double dlatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.updatetTime
     *
     * @mbggenerated
     */
    private Date updatettime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.imail
     *
     * @mbggenerated
     */
    private String imail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.auditingState
     *
     * @mbggenerated
     */
    private String auditingstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.importance
     *
     * @mbggenerated
     */
    private String importance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.papoi
     *
     * @mbggenerated
     */
    private String papoi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.datasourceId
     *
     * @mbggenerated
     */
    private String datasourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.positionCode
     *
     * @mbggenerated
     */
    private String positioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.pid
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.abbreviation
     *
     * @mbggenerated
     */
    private String abbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.geoNum
     *
     * @mbggenerated
     */
    private Long geonum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.albumId
     *
     * @mbggenerated
     */
    private Long albumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.geo_level
     *
     * @mbggenerated
     */
    private Integer geoLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.cover_pic
     *
     * @mbggenerated
     */
    private String coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.shouhui
     *
     * @mbggenerated
     */
    private Long shouhui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.relativeLocation
     *
     * @mbggenerated
     */
    private String relativelocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ia_addresses.contacts
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public IaAddresses(Long addressid, String name, String namepy, String othername, String othernamepy, String oldname, String oldnamepy, String englishname, String address, String telephone, String zipcode, String citycode, String type, Double displayx, Double displayy, Double dlongitude, Double dlatitude, Date created, Date updatettime, String url, String imail, String auditingstate, String importance, String tag, String papoi, String datasourceid, String brand, String positioncode, String pid, String abbreviation, Long geonum, Long userid, Long albumid, Integer geoLevel, String coverPic, Long shouhui, String relativelocation, String contacts) {
        this.addressid = addressid;
        this.name = name;
        this.namepy = namepy;
        this.othername = othername;
        this.othernamepy = othernamepy;
        this.oldname = oldname;
        this.oldnamepy = oldnamepy;
        this.englishname = englishname;
        this.address = address;
        this.telephone = telephone;
        this.zipcode = zipcode;
        this.citycode = citycode;
        this.type = type;
        this.displayx = displayx;
        this.displayy = displayy;
        this.dlongitude = dlongitude;
        this.dlatitude = dlatitude;
        this.created = created;
        this.updatettime = updatettime;
        this.url = url;
        this.imail = imail;
        this.auditingstate = auditingstate;
        this.importance = importance;
        this.tag = tag;
        this.papoi = papoi;
        this.datasourceid = datasourceid;
        this.brand = brand;
        this.positioncode = positioncode;
        this.pid = pid;
        this.abbreviation = abbreviation;
        this.geonum = geonum;
        this.userid = userid;
        this.albumid = albumid;
        this.geoLevel = geoLevel;
        this.coverPic = coverPic;
        this.shouhui = shouhui;
        this.relativelocation = relativelocation;
        this.contacts = contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    public IaAddresses() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.addressId
     *
     * @return the value of ia_addresses.addressId
     *
     * @mbggenerated
     */
    public Long getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.addressId
     *
     * @param addressid the value for ia_addresses.addressId
     *
     * @mbggenerated
     */
    public void setAddressid(Long addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.name
     *
     * @return the value of ia_addresses.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.name
     *
     * @param name the value for ia_addresses.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.namepy
     *
     * @return the value of ia_addresses.namepy
     *
     * @mbggenerated
     */
    public String getNamepy() {
        return namepy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.namepy
     *
     * @param namepy the value for ia_addresses.namepy
     *
     * @mbggenerated
     */
    public void setNamepy(String namepy) {
        this.namepy = namepy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.othername
     *
     * @return the value of ia_addresses.othername
     *
     * @mbggenerated
     */
    public String getOthername() {
        return othername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.othername
     *
     * @param othername the value for ia_addresses.othername
     *
     * @mbggenerated
     */
    public void setOthername(String othername) {
        this.othername = othername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.othernamepy
     *
     * @return the value of ia_addresses.othernamepy
     *
     * @mbggenerated
     */
    public String getOthernamepy() {
        return othernamepy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.othernamepy
     *
     * @param othernamepy the value for ia_addresses.othernamepy
     *
     * @mbggenerated
     */
    public void setOthernamepy(String othernamepy) {
        this.othernamepy = othernamepy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.oldname
     *
     * @return the value of ia_addresses.oldname
     *
     * @mbggenerated
     */
    public String getOldname() {
        return oldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.oldname
     *
     * @param oldname the value for ia_addresses.oldname
     *
     * @mbggenerated
     */
    public void setOldname(String oldname) {
        this.oldname = oldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.oldnamepy
     *
     * @return the value of ia_addresses.oldnamepy
     *
     * @mbggenerated
     */
    public String getOldnamepy() {
        return oldnamepy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.oldnamepy
     *
     * @param oldnamepy the value for ia_addresses.oldnamepy
     *
     * @mbggenerated
     */
    public void setOldnamepy(String oldnamepy) {
        this.oldnamepy = oldnamepy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.englishname
     *
     * @return the value of ia_addresses.englishname
     *
     * @mbggenerated
     */
    public String getEnglishname() {
        return englishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.englishname
     *
     * @param englishname the value for ia_addresses.englishname
     *
     * @mbggenerated
     */
    public void setEnglishname(String englishname) {
        this.englishname = englishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.address
     *
     * @return the value of ia_addresses.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.address
     *
     * @param address the value for ia_addresses.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.telephone
     *
     * @return the value of ia_addresses.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.telephone
     *
     * @param telephone the value for ia_addresses.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.zipcode
     *
     * @return the value of ia_addresses.zipcode
     *
     * @mbggenerated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.zipcode
     *
     * @param zipcode the value for ia_addresses.zipcode
     *
     * @mbggenerated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.citycode
     *
     * @return the value of ia_addresses.citycode
     *
     * @mbggenerated
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.citycode
     *
     * @param citycode the value for ia_addresses.citycode
     *
     * @mbggenerated
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.type
     *
     * @return the value of ia_addresses.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.type
     *
     * @param type the value for ia_addresses.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.displayX
     *
     * @return the value of ia_addresses.displayX
     *
     * @mbggenerated
     */
    public Double getDisplayx() {
        return displayx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.displayX
     *
     * @param displayx the value for ia_addresses.displayX
     *
     * @mbggenerated
     */
    public void setDisplayx(Double displayx) {
        this.displayx = displayx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.displayY
     *
     * @return the value of ia_addresses.displayY
     *
     * @mbggenerated
     */
    public Double getDisplayy() {
        return displayy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.displayY
     *
     * @param displayy the value for ia_addresses.displayY
     *
     * @mbggenerated
     */
    public void setDisplayy(Double displayy) {
        this.displayy = displayy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.dlongitude
     *
     * @return the value of ia_addresses.dlongitude
     *
     * @mbggenerated
     */
    public Double getDlongitude() {
        return dlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.dlongitude
     *
     * @param dlongitude the value for ia_addresses.dlongitude
     *
     * @mbggenerated
     */
    public void setDlongitude(Double dlongitude) {
        this.dlongitude = dlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.dlatitude
     *
     * @return the value of ia_addresses.dlatitude
     *
     * @mbggenerated
     */
    public Double getDlatitude() {
        return dlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.dlatitude
     *
     * @param dlatitude the value for ia_addresses.dlatitude
     *
     * @mbggenerated
     */
    public void setDlatitude(Double dlatitude) {
        this.dlatitude = dlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.created
     *
     * @return the value of ia_addresses.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.created
     *
     * @param created the value for ia_addresses.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.updatetTime
     *
     * @return the value of ia_addresses.updatetTime
     *
     * @mbggenerated
     */
    public Date getUpdatettime() {
        return updatettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.updatetTime
     *
     * @param updatettime the value for ia_addresses.updatetTime
     *
     * @mbggenerated
     */
    public void setUpdatettime(Date updatettime) {
        this.updatettime = updatettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.url
     *
     * @return the value of ia_addresses.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.url
     *
     * @param url the value for ia_addresses.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.imail
     *
     * @return the value of ia_addresses.imail
     *
     * @mbggenerated
     */
    public String getImail() {
        return imail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.imail
     *
     * @param imail the value for ia_addresses.imail
     *
     * @mbggenerated
     */
    public void setImail(String imail) {
        this.imail = imail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.auditingState
     *
     * @return the value of ia_addresses.auditingState
     *
     * @mbggenerated
     */
    public String getAuditingstate() {
        return auditingstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.auditingState
     *
     * @param auditingstate the value for ia_addresses.auditingState
     *
     * @mbggenerated
     */
    public void setAuditingstate(String auditingstate) {
        this.auditingstate = auditingstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.importance
     *
     * @return the value of ia_addresses.importance
     *
     * @mbggenerated
     */
    public String getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.importance
     *
     * @param importance the value for ia_addresses.importance
     *
     * @mbggenerated
     */
    public void setImportance(String importance) {
        this.importance = importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.tag
     *
     * @return the value of ia_addresses.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.tag
     *
     * @param tag the value for ia_addresses.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.papoi
     *
     * @return the value of ia_addresses.papoi
     *
     * @mbggenerated
     */
    public String getPapoi() {
        return papoi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.papoi
     *
     * @param papoi the value for ia_addresses.papoi
     *
     * @mbggenerated
     */
    public void setPapoi(String papoi) {
        this.papoi = papoi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.datasourceId
     *
     * @return the value of ia_addresses.datasourceId
     *
     * @mbggenerated
     */
    public String getDatasourceid() {
        return datasourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.datasourceId
     *
     * @param datasourceid the value for ia_addresses.datasourceId
     *
     * @mbggenerated
     */
    public void setDatasourceid(String datasourceid) {
        this.datasourceid = datasourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.brand
     *
     * @return the value of ia_addresses.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.brand
     *
     * @param brand the value for ia_addresses.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.positionCode
     *
     * @return the value of ia_addresses.positionCode
     *
     * @mbggenerated
     */
    public String getPositioncode() {
        return positioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.positionCode
     *
     * @param positioncode the value for ia_addresses.positionCode
     *
     * @mbggenerated
     */
    public void setPositioncode(String positioncode) {
        this.positioncode = positioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.pid
     *
     * @return the value of ia_addresses.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.pid
     *
     * @param pid the value for ia_addresses.pid
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.abbreviation
     *
     * @return the value of ia_addresses.abbreviation
     *
     * @mbggenerated
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.abbreviation
     *
     * @param abbreviation the value for ia_addresses.abbreviation
     *
     * @mbggenerated
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.geoNum
     *
     * @return the value of ia_addresses.geoNum
     *
     * @mbggenerated
     */
    public Long getGeonum() {
        return geonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.geoNum
     *
     * @param geonum the value for ia_addresses.geoNum
     *
     * @mbggenerated
     */
    public void setGeonum(Long geonum) {
        this.geonum = geonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.userId
     *
     * @return the value of ia_addresses.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.userId
     *
     * @param userid the value for ia_addresses.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.albumId
     *
     * @return the value of ia_addresses.albumId
     *
     * @mbggenerated
     */
    public Long getAlbumid() {
        return albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.albumId
     *
     * @param albumid the value for ia_addresses.albumId
     *
     * @mbggenerated
     */
    public void setAlbumid(Long albumid) {
        this.albumid = albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.geo_level
     *
     * @return the value of ia_addresses.geo_level
     *
     * @mbggenerated
     */
    public Integer getGeoLevel() {
        return geoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.geo_level
     *
     * @param geoLevel the value for ia_addresses.geo_level
     *
     * @mbggenerated
     */
    public void setGeoLevel(Integer geoLevel) {
        this.geoLevel = geoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.cover_pic
     *
     * @return the value of ia_addresses.cover_pic
     *
     * @mbggenerated
     */
    public String getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.cover_pic
     *
     * @param coverPic the value for ia_addresses.cover_pic
     *
     * @mbggenerated
     */
    public void setCoverPic(String coverPic) {
        this.coverPic = coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.shouhui
     *
     * @return the value of ia_addresses.shouhui
     *
     * @mbggenerated
     */
    public Long getShouhui() {
        return shouhui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.shouhui
     *
     * @param shouhui the value for ia_addresses.shouhui
     *
     * @mbggenerated
     */
    public void setShouhui(Long shouhui) {
        this.shouhui = shouhui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.relativeLocation
     *
     * @return the value of ia_addresses.relativeLocation
     *
     * @mbggenerated
     */
    public String getRelativelocation() {
        return relativelocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.relativeLocation
     *
     * @param relativelocation the value for ia_addresses.relativeLocation
     *
     * @mbggenerated
     */
    public void setRelativelocation(String relativelocation) {
        this.relativelocation = relativelocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ia_addresses.contacts
     *
     * @return the value of ia_addresses.contacts
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ia_addresses.contacts
     *
     * @param contacts the value for ia_addresses.contacts
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }
}