package com.iwhere.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class IaCollectedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public IaCollectedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCollectidIsNull() {
            addCriterion("collectId is null");
            return (Criteria) this;
        }

        public Criteria andCollectidIsNotNull() {
            addCriterion("collectId is not null");
            return (Criteria) this;
        }

        public Criteria andCollectidEqualTo(Long value) {
            addCriterion("collectId =", value, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidNotEqualTo(Long value) {
            addCriterion("collectId <>", value, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidGreaterThan(Long value) {
            addCriterion("collectId >", value, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidGreaterThanOrEqualTo(Long value) {
            addCriterion("collectId >=", value, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidLessThan(Long value) {
            addCriterion("collectId <", value, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidLessThanOrEqualTo(Long value) {
            addCriterion("collectId <=", value, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidIn(List<Long> values) {
            addCriterion("collectId in", values, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidNotIn(List<Long> values) {
            addCriterion("collectId not in", values, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidBetween(Long value1, Long value2) {
            addCriterion("collectId between", value1, value2, "collectid");
            return (Criteria) this;
        }

        public Criteria andCollectidNotBetween(Long value1, Long value2) {
            addCriterion("collectId not between", value1, value2, "collectid");
            return (Criteria) this;
        }

        public Criteria andCoverPicIsNull() {
            addCriterion("cover_pic is null");
            return (Criteria) this;
        }

        public Criteria andCoverPicIsNotNull() {
            addCriterion("cover_pic is not null");
            return (Criteria) this;
        }

        public Criteria andCoverPicEqualTo(String value) {
            addCriterion("cover_pic =", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicNotEqualTo(String value) {
            addCriterion("cover_pic <>", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicGreaterThan(String value) {
            addCriterion("cover_pic >", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicGreaterThanOrEqualTo(String value) {
            addCriterion("cover_pic >=", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicLessThan(String value) {
            addCriterion("cover_pic <", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicLessThanOrEqualTo(String value) {
            addCriterion("cover_pic <=", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicLike(String value) {
            addCriterion("cover_pic like", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicNotLike(String value) {
            addCriterion("cover_pic not like", value, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicIn(List<String> values) {
            addCriterion("cover_pic in", values, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicNotIn(List<String> values) {
            addCriterion("cover_pic not in", values, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicBetween(String value1, String value2) {
            addCriterion("cover_pic between", value1, value2, "coverPic");
            return (Criteria) this;
        }

        public Criteria andCoverPicNotBetween(String value1, String value2) {
            addCriterion("cover_pic not between", value1, value2, "coverPic");
            return (Criteria) this;
        }

        public Criteria andFirstletterIsNull() {
            addCriterion("firstLetter is null");
            return (Criteria) this;
        }

        public Criteria andFirstletterIsNotNull() {
            addCriterion("firstLetter is not null");
            return (Criteria) this;
        }

        public Criteria andFirstletterEqualTo(String value) {
            addCriterion("firstLetter =", value, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterNotEqualTo(String value) {
            addCriterion("firstLetter <>", value, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterGreaterThan(String value) {
            addCriterion("firstLetter >", value, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterGreaterThanOrEqualTo(String value) {
            addCriterion("firstLetter >=", value, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterLessThan(String value) {
            addCriterion("firstLetter <", value, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterLessThanOrEqualTo(String value) {
            addCriterion("firstLetter <=", value, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterLike(String value) {
            addCriterion("firstLetter like", value, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterNotLike(String value) {
            addCriterion("firstLetter not like", value, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterIn(List<String> values) {
            addCriterion("firstLetter in", values, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterNotIn(List<String> values) {
            addCriterion("firstLetter not in", values, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterBetween(String value1, String value2) {
            addCriterion("firstLetter between", value1, value2, "firstletter");
            return (Criteria) this;
        }

        public Criteria andFirstletterNotBetween(String value1, String value2) {
            addCriterion("firstLetter not between", value1, value2, "firstletter");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNull() {
            addCriterion("addressId is null");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNotNull() {
            addCriterion("addressId is not null");
            return (Criteria) this;
        }

        public Criteria andAddressidEqualTo(Long value) {
            addCriterion("addressId =", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotEqualTo(Long value) {
            addCriterion("addressId <>", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThan(Long value) {
            addCriterion("addressId >", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThanOrEqualTo(Long value) {
            addCriterion("addressId >=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThan(Long value) {
            addCriterion("addressId <", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThanOrEqualTo(Long value) {
            addCriterion("addressId <=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidIn(List<Long> values) {
            addCriterion("addressId in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotIn(List<Long> values) {
            addCriterion("addressId not in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidBetween(Long value1, Long value2) {
            addCriterion("addressId between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotBetween(Long value1, Long value2) {
            addCriterion("addressId not between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDeleteclassIsNull() {
            addCriterion("deleteClass is null");
            return (Criteria) this;
        }

        public Criteria andDeleteclassIsNotNull() {
            addCriterion("deleteClass is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteclassEqualTo(Integer value) {
            addCriterion("deleteClass =", value, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassNotEqualTo(Integer value) {
            addCriterion("deleteClass <>", value, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassGreaterThan(Integer value) {
            addCriterion("deleteClass >", value, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleteClass >=", value, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassLessThan(Integer value) {
            addCriterion("deleteClass <", value, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassLessThanOrEqualTo(Integer value) {
            addCriterion("deleteClass <=", value, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassIn(List<Integer> values) {
            addCriterion("deleteClass in", values, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassNotIn(List<Integer> values) {
            addCriterion("deleteClass not in", values, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassBetween(Integer value1, Integer value2) {
            addCriterion("deleteClass between", value1, value2, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andDeleteclassNotBetween(Integer value1, Integer value2) {
            addCriterion("deleteClass not between", value1, value2, "deleteclass");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andAlbumidIsNull() {
            addCriterion("albumId is null");
            return (Criteria) this;
        }

        public Criteria andAlbumidIsNotNull() {
            addCriterion("albumId is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumidEqualTo(Long value) {
            addCriterion("albumId =", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidNotEqualTo(Long value) {
            addCriterion("albumId <>", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidGreaterThan(Long value) {
            addCriterion("albumId >", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidGreaterThanOrEqualTo(Long value) {
            addCriterion("albumId >=", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidLessThan(Long value) {
            addCriterion("albumId <", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidLessThanOrEqualTo(Long value) {
            addCriterion("albumId <=", value, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidIn(List<Long> values) {
            addCriterion("albumId in", values, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidNotIn(List<Long> values) {
            addCriterion("albumId not in", values, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidBetween(Long value1, Long value2) {
            addCriterion("albumId between", value1, value2, "albumid");
            return (Criteria) this;
        }

        public Criteria andAlbumidNotBetween(Long value1, Long value2) {
            addCriterion("albumId not between", value1, value2, "albumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidIsNull() {
            addCriterion("sketch_albumId is null");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidIsNotNull() {
            addCriterion("sketch_albumId is not null");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidEqualTo(Long value) {
            addCriterion("sketch_albumId =", value, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidNotEqualTo(Long value) {
            addCriterion("sketch_albumId <>", value, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidGreaterThan(Long value) {
            addCriterion("sketch_albumId >", value, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidGreaterThanOrEqualTo(Long value) {
            addCriterion("sketch_albumId >=", value, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidLessThan(Long value) {
            addCriterion("sketch_albumId <", value, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidLessThanOrEqualTo(Long value) {
            addCriterion("sketch_albumId <=", value, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidIn(List<Long> values) {
            addCriterion("sketch_albumId in", values, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidNotIn(List<Long> values) {
            addCriterion("sketch_albumId not in", values, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidBetween(Long value1, Long value2) {
            addCriterion("sketch_albumId between", value1, value2, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andSketchAlbumidNotBetween(Long value1, Long value2) {
            addCriterion("sketch_albumId not between", value1, value2, "sketchAlbumid");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdIsNull() {
            addCriterion("video_set_id is null");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdIsNotNull() {
            addCriterion("video_set_id is not null");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdEqualTo(Long value) {
            addCriterion("video_set_id =", value, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdNotEqualTo(Long value) {
            addCriterion("video_set_id <>", value, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdGreaterThan(Long value) {
            addCriterion("video_set_id >", value, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdGreaterThanOrEqualTo(Long value) {
            addCriterion("video_set_id >=", value, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdLessThan(Long value) {
            addCriterion("video_set_id <", value, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdLessThanOrEqualTo(Long value) {
            addCriterion("video_set_id <=", value, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdIn(List<Long> values) {
            addCriterion("video_set_id in", values, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdNotIn(List<Long> values) {
            addCriterion("video_set_id not in", values, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdBetween(Long value1, Long value2) {
            addCriterion("video_set_id between", value1, value2, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andVideoSetIdNotBetween(Long value1, Long value2) {
            addCriterion("video_set_id not between", value1, value2, "videoSetId");
            return (Criteria) this;
        }

        public Criteria andCategoryidIsNull() {
            addCriterion("categoryId is null");
            return (Criteria) this;
        }

        public Criteria andCategoryidIsNotNull() {
            addCriterion("categoryId is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryidEqualTo(Long value) {
            addCriterion("categoryId =", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidNotEqualTo(Long value) {
            addCriterion("categoryId <>", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidGreaterThan(Long value) {
            addCriterion("categoryId >", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidGreaterThanOrEqualTo(Long value) {
            addCriterion("categoryId >=", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidLessThan(Long value) {
            addCriterion("categoryId <", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidLessThanOrEqualTo(Long value) {
            addCriterion("categoryId <=", value, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidIn(List<Long> values) {
            addCriterion("categoryId in", values, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidNotIn(List<Long> values) {
            addCriterion("categoryId not in", values, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidBetween(Long value1, Long value2) {
            addCriterion("categoryId between", value1, value2, "categoryid");
            return (Criteria) this;
        }

        public Criteria andCategoryidNotBetween(Long value1, Long value2) {
            addCriterion("categoryId not between", value1, value2, "categoryid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ia_collected
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}