package com.iwhere.mybatis.dao;

import com.iwhere.mybatis.model.IaAddresses;
import com.iwhere.mybatis.model.IaAddressesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IaAddressesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int countByExample(IaAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int deleteByExample(IaAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long addressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int insert(IaAddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int insertSelective(IaAddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    List<IaAddresses> selectByExample(IaAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    IaAddresses selectByPrimaryKey(Long addressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IaAddresses record, @Param("example") IaAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IaAddresses record, @Param("example") IaAddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IaAddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_addresses
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IaAddresses record);
}