package com.iwhere.mybatis.dao;

import com.iwhere.mybatis.model.IaCollected;
import com.iwhere.mybatis.model.IaCollectedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IaCollectedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int countByExample(IaCollectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int deleteByExample(IaCollectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long collectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int insert(IaCollected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int insertSelective(IaCollected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    List<IaCollected> selectByExample(IaCollectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    IaCollected selectByPrimaryKey(Long collectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IaCollected record, @Param("example") IaCollectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IaCollected record, @Param("example") IaCollectedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IaCollected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ia_collected
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IaCollected record);
}